services:
  postgres:
    image: postgres:16
    container_name: stonehub-postgres
    environment:
      POSTGRES_DB: stonehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - stonehub-postgres-data:/var/lib/postgresql/data

volumes:
  stonehub-postgres-data:
